### ISSUE TITLE
有关lVENCalculatorInputView问题

### ISSUE THREAD

**Issue by samliu613** [XinStar1/AZXTallyBook#1]
非常感谢您发布的这个记账软件代码，我在学习您的代码直接编译时出现：
ld: library not found for -lVENCalculatorInputView
clang: error: linker command failed with exit code 1 (use -v to see invocation)
错误，导致无法编译运行，请问我是这边设置还是需要额外加载模块原因呢？多谢

**Comment by XinStar1** [comment]
你好，我这边刚刚测试了一下没有问题，你是直接整个项目zip打包下载下来的么？  如果还不行我试试用别的电脑看能不能发现问题

**Comment by samliu613** [comment]
谢谢回复，是zip打包下载下来的。不是您那边的问题。我打开.xcworkspace文件就可以了，之前打开.xcodeproj报错。
